"""Reusable citation formatting for research reports.

What this module is not
-------------------------
Atlas's query engine is explicitly deterministic and rule-based — no LLM
calls (see engine.py's module docstring). This module does not generate
analytical prose ("management is optimistic because..."); that judgment is
made by whoever writes the report (a human analyst, or an LLM reading the
underlying transcripts), the same way it always has been. What this module
DOES own is turning that judgment's supporting evidence into professional,
consistent citations — the mechanical part that was previously hand-written
prose per report, sometimes as a bare evidence_id, sometimes not at all.

Design
------
A Finding pairs a claim with the evidence_ids that support it. render()
formats a list of Findings as a plain-text/markdown report section: a
single supporting document becomes a "Source:" block (citation_full, with
section/page when the Finding carries provenance); more than one becomes a
"Supporting evidence" bulleted list (citation_standard each) — this is
exactly the grouping behaviour asked for, driven by how many evidence_ids
a Finding actually has, not a fixed style choice.

Every evidence_id must still resolve through the same repo/profile
back-links atlas.citation already uses — no separate index, no duplicated
metadata.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from atlas.acquisition.repository import Repository
from atlas.citation import Citation, build_citation
from atlas.company.model import CompanyProfile


@dataclass
class Finding:
    """One claim in a research report, plus the evidence backing it.

    text:         the claim/statement itself (the analyst's or LLM's
                  judgment — not generated by this module).
    evidence_ids: one or more supporting documents. Order is preserved.
    section:      optional Provenance-style section label for a single-
                  source finding's "Source:" block (e.g. "Business Outlook").
    page:         optional page number; never fabricated — omitted from
                  output whenever not supplied, same as atlas.citation.
    kind:         "fact" (default) or "synthesis" — distinguishes a claim
                  read directly off extracted data from an interpretive
                  connection across multiple facts (e.g. "3 consecutive
                  quarters of margin improvement" is synthesis; the margin
                  figure itself is fact). Added for Atlas Research v1;
                  defaults to "fact" so every pre-existing Finding call site
                  is unaffected.
    """

    text: str
    evidence_ids: list[str] = field(default_factory=list)
    section: str | None = None
    page: int | None = None
    kind: str = "fact"


def _citations_for(
    finding: Finding, ticker: str, repo: Repository, profile: CompanyProfile | None,
) -> list[Citation]:
    citations = []
    for eid in finding.evidence_ids:
        entry = repo.get(eid)
        if entry is None:
            continue
        section = finding.section if len(finding.evidence_ids) == 1 else None
        page = finding.page if len(finding.evidence_ids) == 1 else None
        citations.append(build_citation(entry, ticker, profile, section=section, page=page))
    return citations


def render_finding(
    finding: Finding, ticker: str, repo: Repository, profile: CompanyProfile | None = None,
) -> str:
    """Render one Finding as text + its citation block.

    One supporting document -> "Source:" + citation_full (section/page
    included when the Finding carries them). More than one -> "Supporting
    evidence" + a bulleted citation_standard list, since several
    independent documents corroborating the same claim is a materially
    different (stronger) kind of evidence than a single source, and the
    reader should see that at a glance rather than a flat list of names.
    """
    lines = [finding.text, ""]
    citations = _citations_for(finding, ticker, repo, profile)

    if not citations:
        lines.append("Source: (evidence unavailable)")
    elif len(citations) == 1:
        lines.append("Source:")
        for line in citations[0].citation_full.split("\n"):
            lines.append(line)
    else:
        lines.append("Supporting evidence:")
        for c in citations:
            lines.append(f"  - {c.citation_standard}")

    return "\n".join(lines)


def render_report(
    title: str,
    findings: list[Finding],
    ticker: str,
    repo: Repository,
    profile: CompanyProfile | None = None,
) -> str:
    """A complete plain-text report: a title, then each Finding with its
    citation block, blank-line separated."""
    blocks = [title, "=" * len(title), ""]
    for finding in findings:
        blocks.append(render_finding(finding, ticker, repo, profile))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"
