"""Investigation executor (M2.2.5 commit 3).

Runs a ``ResearchPlan``'s investigations and turns each one into a
``Finding`` -- the type ``research/citations.py`` already defines and the
deterministic report already renders. No new claim type is introduced:
``Finding``'s docstring already anticipates exactly this caller, describing
its ``text`` as "the analyst's or LLM's judgment -- not generated by this
module."

Where this sits
---------------
    ResearchPlanner  -> WHAT to investigate          (planner.py)
    RetrievalPlanner -> HOW to retrieve each one     (reasoning/planner.py)
    THIS MODULE      -> executes them                (no planning, no synthesis)
    M2.3             -> forms the view from results  (not here)

Each ``Investigation.question`` is passed to ``plan_retrieval()`` verbatim and
then through the existing ``build_context_with_diagnostics`` -> ``ask`` ->
``to_answer`` path. Nothing about retrieval or reasoning is re-implemented
here; this module is composition only.

The provenance rule, made structural
------------------------------------
``InvestigationResult`` cannot represent an ungrounded claim. It holds EITHER
a ``Finding`` carrying at least one ``evidence_id``, OR an
``unresolved_reason`` -- never both, never neither, enforced in
``__post_init__``. A refusal, a retrieval miss, or an executor error all
become explicit unresolved results rather than a confident sentence with no
citation behind it. This is the precondition M2.3's synthesis gate depends on:
it can only cite what this module actually grounded.

One failing investigation never aborts the run -- the same batch-robustness
rule ``eval/runner.py``'s ``_run_case`` already applies to eval cases, for the
same reason: a six-dimension research run that dies on dimension three is
strictly less useful than one that reports five findings and one failure.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from atlas.company.model import CompanyProfile
from atlas.company.store import CompanyStore
from atlas.knowledge.base import KnowledgeBase
from atlas.reasoning.ask import ask
from atlas.reasoning.context import build_context_with_diagnostics
from atlas.reasoning.contracts import Question, SubjectRef
from atlas.reasoning.llm import LLMClient
from atlas.reasoning.plan import SearchPlan
from atlas.reasoning.planner import plan_retrieval
from atlas.reasoning.render import to_answer
from atlas.reasoning.retrieval import RetrievalResult
from atlas.research.citations import Finding
from atlas.research.plan import Investigation, ResearchPlan


class InvestigationError(RuntimeError):
    """An investigation could not be executed (e.g. missing profile)."""


@dataclass(frozen=True)
class InvestigationResult:
    """One investigation's outcome: a grounded Finding, or an explicit
    statement that it could not be grounded. Never a claim without evidence.
    """

    investigation: Investigation
    finding: Finding | None = None
    unresolved_reason: str | None = None
    plan: SearchPlan | None = None
    retrieval: RetrievalResult | None = None

    def __post_init__(self) -> None:
        if (self.finding is None) == (self.unresolved_reason is None):
            raise ValueError(
                "InvestigationResult must carry exactly one of finding / "
                f"unresolved_reason (dimension {self.investigation.dimension!r})"
            )
        if self.finding is not None and not self.finding.evidence_ids:
            raise ValueError(
                "InvestigationResult.finding must carry at least one evidence_id -- "
                "an ungrounded claim must be recorded as unresolved instead "
                f"(dimension {self.investigation.dimension!r})"
            )

    @property
    def resolved(self) -> bool:
        return self.finding is not None


@dataclass(frozen=True)
class InvestigationRun:
    """A whole research plan, executed."""

    plan: ResearchPlan
    results: tuple[InvestigationResult, ...]

    @property
    def findings(self) -> tuple[Finding, ...]:
        """Every grounded Finding, in execution order -- M2.3's input."""
        return tuple(r.finding for r in self.results if r.finding is not None)

    @property
    def unresolved(self) -> tuple[InvestigationResult, ...]:
        return tuple(r for r in self.results if r.finding is None)

    @property
    def resolution_rate(self) -> float:
        if not self.results:
            return 0.0
        return round(len(self.findings) / len(self.results), 3)


def _load_subject(repo_base: Path, subject: str) -> tuple[CompanyProfile, KnowledgeBase | None]:
    repo_root = repo_base / subject
    profile_path = repo_root / "profile.json"
    if not profile_path.exists():
        raise InvestigationError(f"no profile for {subject!r}")
    profile = CompanyStore(profile_path, subject).load()
    kb = KnowledgeBase(repo_root) if (repo_root / "knowledge.db").exists() else None
    return profile, kb


def run_investigation(
    investigation: Investigation,
    repo_base: Path,
    client: LLMClient,
) -> InvestigationResult:
    """Execute one investigation. Never raises: every failure mode becomes an
    unresolved result, so a caller iterating a plan cannot be aborted by one
    bad dimension.

    Multi-subject investigations (comparison intents) currently ground against
    the FIRST subject's profile and knowledge base. This is a deliberate,
    visible limitation rather than a silent one -- true multi-subject grounding
    is M2.2's contribution, and when it lands this function changes here only.
    """
    try:
        subject_id = investigation.subjects[0]
        profile, kb = _load_subject(repo_base, subject_id)
        subject_ref = SubjectRef(subject_id=subject_id, display=subject_id)

        plan = plan_retrieval(investigation.question)
        build_result = build_context_with_diagnostics(
            profile, subject_ref, kb=kb, question=investigation.question, plan=plan,
        )
        context = build_result.context

        result = ask(
            Question(raw_text=investigation.question, subject_ref=subject_ref),
            context,
            client,
        )
        answer = to_answer(result, context=context)
    except Exception as exc:  # noqa: BLE001 - one investigation must not abort the run
        return InvestigationResult(
            investigation=investigation,
            unresolved_reason=f"execution error: {exc}",
        )

    if answer.refused:
        return InvestigationResult(
            investigation=investigation,
            unresolved_reason=f"refused: {answer.refusal_reason}",
            plan=plan,
            retrieval=build_result.retrieval,
        )

    evidence_ids = [c.evidence_id for c in answer.citations]
    if not evidence_ids:
        # An answer with no citation cannot become a Finding -- the whole
        # point of the provenance rule. Recorded, not discarded silently.
        return InvestigationResult(
            investigation=investigation,
            unresolved_reason="answered without any citation; not recorded as a finding",
            plan=plan,
            retrieval=build_result.retrieval,
        )

    return InvestigationResult(
        investigation=investigation,
        finding=Finding(
            text=answer.prose,
            evidence_ids=evidence_ids,
            kind="fact",
        ),
        plan=plan,
        retrieval=build_result.retrieval,
    )


def run_plan(
    plan: ResearchPlan,
    repo_base: Path,
    client: LLMClient,
) -> InvestigationRun:
    """Execute every investigation in priority order.

    ``client`` is required: this is the executing path. The plan-only path
    (``--dry-run``) never calls this function at all and builds no LLM client
    whatsoever -- see ``cli.py``'s ``investigate`` command.
    """
    results = tuple(
        run_investigation(inv, repo_base, client)
        for inv in plan.ordered_investigations()
    )
    return InvestigationRun(plan=plan, results=results)
